services:
  - type: web
    name: hamster-api
    runtime: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --bind 0.0.0.0:$PORT api_server:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: TWELVE_DATA_API_KEY
        sync: false
