services:
  - type: web
    name: hamster-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT api_server:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: TWELVE_DATA_API_KEY
        sync: false
