services:
  - type: web
    name: hamsterterminal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m http.server 8000 --bind 0.0.0.0
    routes:
      - path: /
        matchType: prefix
    staticPublicPath: ./
    envVars:
      - key: PORT
        value: 8000
